name: Check prod release merge

on:
  pull_request:
    types: [opened]
    branches:
      - latest

permissions:
  contents: write # for checkout and tag
  pull-requests: write # for comments
  packages: write # for publish

jobs:
  check:
    name: log
    runs-on: ubuntu-latest

      steps:
        - name: log
          run: |
          echo ${{github.ref_name}} ${{github.head_ref}}

